const BOILERPLATE_PATTERNS = [
  /\bgmail\s*images\b/i,
  /\bhow search works\b/i,
  /\bprivacy\b/i,
  /\bterms\b/i,
  /\badvertising\b/i,
  /\bbusiness\b/i,
  /\boffered in\b/i,
  /\bsubscribe\b/i,
  /\bclick the bell\b/i,
  /\bbackground picture by\b/i,
  /\bcontact\/submissions\b/i,
  /\bbased on sources\b/i,
  /\bthis summary was generated by ai\b/i,
];

function normalizeText(value) {
  return String(value || "").replace(/\s+/g, " ").trim();
}

function normalizeRichText(value) {
  return String(value || "")
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    .split(/\n{2,}/)
    .map((block) =>
      block
        .split(/\n+/)
        .map((line) => line.replace(/[ \t]+/g, " ").trim())
        .filter(Boolean)
        .join("\n")
    )
    .filter(Boolean)
    .join("\n\n")
    .trim();
}

function score01(value) {
  return Math.max(0, Math.min(1, Number(value || 0)));
}

function candidateLines(profile) {
  const fullText = normalizeRichText(profile?.fullText || profile?.displayFullText || "");
  const snippet = normalizeText(profile?.snippet || "");
  const source = fullText || snippet;
  if (!source) {
    return [];
  }
  return source
    .split(/\n+|(?<=[.!?])\s+(?=[A-Z])/)
    .map((line) => normalizeText(line))
    .filter(Boolean);
}

function isBoilerplateLine(line) {
  if (!line) {
    return true;
  }
  if (/^[\-=*_#|.]{6,}$/.test(line)) {
    return true;
  }
  if (/https?:\/\/\S+/i.test(line) && line.length < 180) {
    return true;
  }
  return BOILERPLATE_PATTERNS.some((pattern) => pattern.test(line));
}

function punctuationDensity(line) {
  const text = normalizeText(line);
  if (!text) {
    return 0;
  }
  const matches = text.match(/[.!?:,;]/g);
  return (matches?.length || 0) / Math.max(text.length, 1);
}

export function auditCapturedContent(profile, captureIntent = null) {
  const lines = candidateLines(profile);
  const fullText = normalizeRichText(profile?.fullText || profile?.displayFullText || "");
  const snippet = normalizeText(profile?.snippet || "");
  const unique = new Set(lines.map((line) => line.toLowerCase()));
  const lineCount = lines.length;
  const duplicateLineRatio = lineCount ? 1 - unique.size / lineCount : 0;
  const boilerplateCount = lines.filter((line) => isBoilerplateLine(line)).length;
  const boilerplateRatio = lineCount ? boilerplateCount / lineCount : 0;
  const shortLabelCount = lines.filter((line) => line.length <= 18).length;
  const shortLabelRatio = lineCount ? shortLabelCount / lineCount : 0;
  const urlOnlyCount = lines.filter((line) => /^https?:\/\/\S+$/i.test(line)).length;
  const urlLineRatio = lineCount ? urlOnlyCount / lineCount : 0;
  const punctuationAverage =
    lineCount ? lines.reduce((total, line) => total + punctuationDensity(line), 0) / lineCount : 0;
  const usefulLineCount = lines.filter((line) => !isBoilerplateLine(line) && line.length >= 24).length;
  const usefulRatio = lineCount ? usefulLineCount / lineCount : 0;
  const collapsedCamelHits = (fullText.match(/[a-z][A-Z]/g) || []).length;

  const clutterScore = score01(
    boilerplateRatio * 0.34 +
      duplicateLineRatio * 0.24 +
      shortLabelRatio * 0.12 +
      urlLineRatio * 0.08 +
      (collapsedCamelHits >= 6 ? 0.16 : collapsedCamelHits >= 3 ? 0.08 : 0) +
      (lineCount <= 2 && fullText.length < 180 ? 0.12 : 0)
  );

  const organizationScore = score01(
    usefulRatio * 0.5 +
      (punctuationAverage >= 0.03 ? 0.14 : 0) +
      (duplicateLineRatio <= 0.16 ? 0.14 : 0) +
      (boilerplateRatio <= 0.15 ? 0.12 : 0) +
      (lineCount >= 3 ? 0.1 : 0)
  );

  const issues = [];
  if (boilerplateRatio >= 0.28) {
    issues.push("boilerplate-heavy");
  }
  if (duplicateLineRatio >= 0.18) {
    issues.push("repeated-lines");
  }
  if (shortLabelRatio >= 0.44) {
    issues.push("label-heavy");
  }
  if (urlLineRatio >= 0.18) {
    issues.push("url-heavy");
  }
  if (collapsedCamelHits >= 6) {
    issues.push("collapsed-text");
  }
  if (organizationScore <= 0.34) {
    issues.push("weak-structure");
  }

  let cleaningPlan = "keep";
  if (captureIntent?.shouldSkip) {
    cleaningPlan = "skip";
  } else if (clutterScore >= 0.78 && usefulLineCount <= 1) {
    cleaningPlan = "skip";
  } else if (captureIntent?.shouldKeepMetadataOnly) {
    cleaningPlan = "metadata_only";
  } else if (captureIntent?.shouldPreferStructured || clutterScore >= 0.62) {
    cleaningPlan = "structured_only";
  } else if (clutterScore >= 0.38) {
    cleaningPlan = "clean";
  }

  return {
    version: 1,
    clutterScore: Number(clutterScore.toFixed(4)),
    organizationScore: Number(organizationScore.toFixed(4)),
    lineCount,
    usefulLineCount,
    duplicateLineRatio: Number(duplicateLineRatio.toFixed(4)),
    boilerplateRatio: Number(boilerplateRatio.toFixed(4)),
    issues,
    cleaningPlan,
    shouldSkip: cleaningPlan === "skip",
    shouldPreferStructured: cleaningPlan === "structured_only",
    shouldTrimFullText: cleaningPlan === "clean" || cleaningPlan === "structured_only",
    summary:
      cleaningPlan === "skip"
        ? "Captured content is too cluttered to keep."
        : cleaningPlan === "structured_only"
          ? "Prefer the structured view over the raw captured text."
          : cleaningPlan === "clean"
            ? "Keep this page, but de-noise the captured text."
            : "Captured content is well organized enough to keep.",
    textSample: normalizeText(fullText || snippet).slice(0, 220),
  };
}
